# Generated by Django 4.2.7 on 2023-11-14 16:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userdata",
            old_name="name",
            new_name="fullname",
        ),
    ]
